### ISSUE TITLE
Salvaged skill adj not factoring into xp gain formula when salvaging items

### ISSUE THREAD

**Issue by Midniz** [IronWillGames/AshenEmpires#200]
Salvaging while wearing salvaged armor does not give xp increase commiserate with level increase

**Comment by hgesler** [comment]
Fixed for upcoming patch; the way salvaging has always worked though has been bonus exp based off of 
- use of special items (veldan's tongs, arna's gilded tools etc)
- player total strength or intelligence depending what was being salvaged

Prior to this fix, it is using half of the str/int for difficulty test, then using bonus from the tools for exp.

Changing it so that the players tools, equipment (such as the garbage gear from fishing quest), and str/int add to the difficulty and exp checks. Still halved for the adjusted skill values.
