### ISSUE TITLE
System Message plaque being printed on the char select screen when entering the world if it pops up while char is loading

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/AshenEmpires#34]
System Message plaque being printed on the char select screen when entering the world

Not sure at what point this is being drawn during loading process, but its there and looks a bit off.

![image](https://user-images.githubusercontent.com/74884462/188949055-7350e3c3-abcc-4183-8670-8a4772b87240.png)

**Comment by davidjreese** [comment]
This is works as designed. It normally appears in the play area but since the play area isn't there yet it defaults to the top of the screen.

I am open to suggestions on what to do with it. Since it is just a system message, it could contain information related to the connection process itself (like server failed to connect or something) so we have to show it.
