### ISSUE TITLE
Damage / Heal Casting Distance

### ISSUE THREAD

**Issue by Plutoooooooooooo** [IronWillGames/AshenEmpires#7]
Possibly can't kill quite a few bosses on H & L due to the new healing distances - mages may have to stand in silence range 
Healing / attack distance was reduced when the Party Window Healing was brought in, however it has been reduced to a point where mages may not be able to stay out of silence range for bosses. 
Projection, Nith, GoL, Mukk - any boss that silences.

**Comment by davidjreese** [comment]
Issue duped this:
- https://github.com/IronWillGames/AshenEmpires/issues/10

**Comment by davidjreese** [comment]
I don't think the two are related. I am guessing this range restriction is something else. i read the code and don't see anything obvious. some spells are LOS, so some more data would be helpful.

- what spell and where was the target exactly?
- same problem exists with ranged weapons?
- are these just on oversized creatures or something too with large radius (or is this just healing)? vs working fine on normal sized things?
- does the target appear briefly when you click on the player to heal then blink off?

Thanks

**Comment by GM-Odran** [comment]
what spell and where was the target exactly? - (Healing another player with "Sustaining Heal" or using any damage spell on any mob)
same problem exists with ranged weapons? (Spells only)
are these just on oversized creatures or something too with large radius (or is this just healing)? vs working fine on normal sized things? (On all things)
does the target appear briefly when you click on the player to heal then blink off? (unsure will check when home)

**It's to do with the heal distance cap that was introduced for the party window healing.**

**Comment by GM-Odran** [comment]
![Screenshot 2022-09-05 123255](https://user-images.githubusercontent.com/112826917/188349854-e6ac3522-e4ba-4480-b785-f7753bcc848c.jpg)
![Screenshot 2022-09-05 123309](https://user-images.githubusercontent.com/112826917/188349857-8025f61a-9e02-4745-bdd5-e344baa784b5.jpg)
![Screenshot 2022-09-05 123235](https://user-images.githubusercontent.com/112826917/188349860-28de1700-8c9d-4381-aa0d-f8f92bb202d5.jpg)

**Comment by EJaynes** [comment]
I posted these late to the party on the other thread:

Ranged weapons work fine. Click to target works appropriately for regular attacks with ranged weapons or magic missile. It's just trying to cast spells at the top or bottom edge of screen that appear to be an issue. The feet have to be a full tile up from the bottom of the play area in order to allow casting, and the top of the window can be touchy as well currently on live environment.


Superior heal on another player who is partially off-screen to the South of your character used to be an option. As long as you could see something to click on, you could heal that character. Now it will not heal unless that player is about two tiles north of that position where you can only see the top of the paperdoll character.

**Comment by davidjreese** [comment]
okay, thanks - this helps me focus where to look

**Comment by davidjreese** [comment]
Pretty sure I found it. This isn't related to the party healing. It was a fix where the code was a general casting fix where casting was incorrectly letting someone target an object if EITHER the X or Y distance was valid (not both). Once I forced it to be both that revealed that the Y disstance test was 1 tile too strict with the screen shift for perspective
